### ISSUE TITLE
python didkit examples - readme update suggestions

### ISSUE THREAD

**Issue by owocki** [spruceid/didkit#106]
```
$ python3 -m pip install django-qr-code django
```
should be 
```
$ python3 -m pip install django-qr-code django didkit
```

**Comment by owocki** [comment]
fwiw i cant seem to install via the make command. looks like im missing a dependancy?

```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/didkit~ % make -C lib ../target/test/python.stamp         (git)-[main] :
cargo build --lib --release
make: cargo: No such file or directory
make: *** [../target/release/libdidkit.so] Error 1
```

**Comment by owocki** [comment]
these are all comments on https://github.com/spruceid/didkit/tree/main/examples/python_django

**Comment by wyc** [comment]
Thanks @owocki, we'll update the instructions to include installation of Rust. For now, you can follow the instructions from https://rustup.rs/

**Comment by owocki** [comment]
installing rust now, i guess i need to follow the readme in the root of repo too before i get to the python one?

fwiw python on my local doesnst seem to know about my `pip3 install didkit` .  

```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/didkit/examples/python_django~ % python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    import didkit
ModuleNotFoundError: No module named 'didkit'
```

**Comment by clehner** [comment]
Hi @owocki,
DIDKit is not yet on PyPI except as a placeholder, so must be built from this repo currently. The `make` command you ran should do this.

**Comment by owocki** [comment]
i am such a script kiddie. thanks, installing rust + the makecommand now

**Comment by owocki** [comment]
currently seems stuck on 

```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/didkit~ % docker login ghcr.io -u OWOCKI --password-stdin (git)-[main] :
```

gotta go do dad stuff, will try again l8er

**Comment by wyc** [comment]
@owocki could you please try following the instructions here to install the package on Linux? https://github.com/spruceid/didkit/tree/main/lib/python

Assuming Ubuntu and bash, it would look like this:
```
$ sudo apt install -y python3-pip python3-virtualenv
$ python3 -m pip install --upgrade pip build
$ cargo build --release
$ python3 -m build
$ python3 -m pip install dist/didkit-`cat setup.cfg | grep version | cut -d' ' -f3`-*.whl
```

After that, the Django example should run with the `didkit` Python package installed. You'd go to `didkit/examples/python_django` and try again to:
```
$ python3 manage.py migrate
$ python3 manage.py runserver
```

**Comment by bumblefudge** [comment]
Package has been added to pipy.
