### ISSUE TITLE
Duplicate crypto functionality

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#113]
`openssl` and `ring` are both included in the default build now, since `hyper-tls` uses `native-tls` which uses `openssl` (on Linux). Should we try to minimize this duplication of functionality? It increases build times and space usage, and may increase the binary sizes). We could switch from `hyper-tls` to `hyper-rustls`, as `rustls` uses `ring`. Or we could switch from `ring` to `openssl`, since `openssl` includes RSA functionality. Or support both `ring` and `openssl` but default to one or the other (this increases complexity of feature flags, but may be useful). I'm not sure how `ring` and `openssl` compare or what use cases will require one or the other. I heard that `openssl` has a better RSA implementation. It also may require additional dependencies: `openssl-dev` and `pkg-config`, as mentioned in #46; or Perl and Clang if using the vendored feature - as mentioned in the readme under `lib/android`.

**Comment by wyc** [comment]
Would love to minimize duplication of functionality wherever possible. We should think about an approach that will allow DIDKit users to completely omit some dependency trees for target environments that offer native handling, such as hardware P-256 support on Android/iOS. Of course, users should also be able to rely on userspace dependencies if they prefer those, even if the target environment has native support.

**Comment by wyc** [comment]
To make this manageable, I feel that we probably need to solve the problem in `ssi` by providing abstracted interfaces for cryptographic libraries and possibly HTTPS components, which can automatically satisfy and resolve cryptographic backends based on target environment and user preferences given at compile-time. Do you think this is the right place to solve it?

**Comment by clehner** [comment]
Sounds like supporting both `openssl` and `ring` is good, but both shouldn't be included unnecessarily.

This issue probably should have been opened on `ssi`, since that is where the dependencies on `hyper-tls` and `ring` are.

In `ssi` we support multiple crypto implementations via features, but a more abstract interface could be interesting. I wonder if it would help maintainability to decouple the main library from the optional dependencies by e.g. isolating use of optional crates into single modules implementing some trait(s).

I think in `ssi` we could continue and improve on using features and target detection to select dependencies. We also have to manage the complexity of features flowing through the dependency graph within `ssi`+`didkit` and might be able to make some improvements there.

**Comment by wyc** [comment]
Maybe we can create a totally separate library that knows about target platforms and their supported cryptographic libraries. This project could manage a dependency graph as an additional utility or part of the build system, to be used by other Rust projects. Perhaps a good first step in this direction is moving `ssi` towards this abstract interface so eventually this piece could just be plucked out.
