### ISSUE TITLE
Intermittent did:web

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#114]
This CI run failed due to a timeout in a test that involves resolving a `did:web`: https://github.com/spruceid/didkit/runs/2142847953#step:14:53

>  ● Verify Credential API - Interop › Can verify verifiable credential Permanent Resident Card, with issuer DID method did:web:vc.transmute.world and linked data proof suite Ed25519Signature2018, fixture case-5 › should fail with mutated proof value
>
>    : Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error:

Rerunning the build, it passes that step without error: https://github.com/spruceid/didkit/runs/2142932722

Should we try to prevent this type of failure by making `did:web` resolution use a local cached copy for testing?

Edit: `reqwest` uses the `https_proxy` environmental variable by default. So we could use a HTTP proxy to intercept the `did:web` request. But we would still need to disable TLS in the request, or make the client request a different URL, or make the client accept a self-signed HTTPS certificate. That will probably need a CLI option or env var for `didkit-http`. Or we could make `didkit-http` use a cache directory on the filesystem for requests, and pre-populate the directory with our cached copy of the DID document. Maybe change the `didkit-http` `-r` fallback resolver option to override the built-in `did:web` support?

**Comment by wyc** [comment]
Sounds like a good solution to me.

**Comment by sbihel** [comment]
In my opinion, we will move to our own runners in the future and we can put a proxy like Squid permanently. But because we haven't had any issue recently I'd be in favour of closing this issue and reopening it later if needed?
