### ISSUE TITLE
DIDKit Feature request: [FEATURE] New command did-key-to-key

### ISSUE THREAD

**Issue by Arxcis** [spruceid/didkit#120]
**Is your feature request related to a problem? Please describe.**
I have a `did:key` already in my Rust-program, and `didkit` requires a `.jwk`-file, for me to do anything. I need an easy way to convert my `did:key` to a `.jwk`-file.

**Describe the solution you'd like**
I would like a new command which mirrors the existing [`didkit key-to-did-key -k <path to jwk>`](https://spruceid.dev/docs/didkit/example--core-functions-in-bash#generate-a-didkey-document):

Demo of what I would like:
```
didkit did-key-to-key <did:key>
```
Should return a `jwk` derived from the `did:key`.

**Describe alternatives you've considered**
- I have looked for, but not found any other CLI's like `didkit` for VC's.
- I have looked for, but not found any Rust libraries for VC's.
- I have looked at https://crates.io/crates/jsonwebtoken, but I am not sure how I should use it with a `did:key` as input, to generate a `jwk`.

**Comment by clehner** [comment]
Hi @Arxcis, thanks for your interest.

`did:key` encodes a public key. `didkit` uses JWK files for private keys, i.e. for signing (creating linked data proofs / issuing VCs/VPs). If we convert a `did:key` to a JWK, it would be a public key JWK only, which could not be used for signing. Do you have an existing private key for your `did:key` in a non-JWK format that you want to be able to convert? Or do you really just want the public key as a JWK?

**Comment by Arxcis** [comment]
@clehner Ok, I can see that I made a mistake in description. I failed to consider the private key. Yes I want to use the JWK for signing :thinking: 

I am using a Rust-libraries to generate the secret and did:key:
```rust
let secret = ed25519_dalek::SecretKey::generate(&mut csprng).as_bytes();
let keypair = did_key::Ed25519KeyPair::from_seed(&secret);
```

**Comment by clehner** [comment]
@Arxcis
Currently to use DIDKit from Rust you may need to use the underlying library `ssi`:
https://github.com/spruceid/ssi/

We don't currently have functions to convert directly from a `ed25519-dalek` or `did_key` keypair into a JWK, but here is how to do it in examples; I hope this helps:

### Ed25519KeyPair to JWK

Convert a `did_key::Ed25519KeyPair` into a `ssi` [JWK](https://rust.didkit.dev/ssi/jwk/struct.JWK.html) struct and print it:
```rust
/*
[dependencies]
ed25519-dalek = { path = "../ssi", default-features = false, features = ["ed25519-dalek", "rand", "sha2"] }
did-key = "0.0.11"
ed25519-dalek = "1"
rand = "0.7"
*/

fn main() {
    use did_key::KeyMaterial;
    let mut csprng = rand::rngs::OsRng {};
    let secret = ed25519_dalek::SecretKey::generate(&mut csprng).to_bytes();
    let didkey = did_key::Ed25519KeyPair::from_seed(&secret);
    let jwk = ssi::jwk::JWK {
        params: ssi::jwk::Params::OKP(ssi::jwk::OctetParams {
            curve: "Ed25519".to_string(),
            public_key: ssi::jwk::Base64urlUInt(didkey.public_key_bytes()),
            private_key: Some(ssi::jwk::Base64urlUInt(didkey.private_key_bytes())),
        }),
        public_key_use: None,
        key_operations: None,
        algorithm: None,
        key_id: None,
        x509_url: None,
        x509_certificate_chain: None,
        x509_thumbprint_sha1: None,
        x509_thumbprint_sha256: None,
    };
    println!("{}", serde_json::to_string(&jwk).unwrap());
}
```

### Keypair to JWK

Convert a `ed25519-dalek` keypair into a `ssi` [JWK](https://rust.didkit.dev/ssi/jwk/struct.JWK.html) struct and print it:
```rust
/*
[dependencies]
ssi = { path = "../ssi", default-features = false, features = ["ed25519-dalek", "rand", "sha2"] }
ed25519-dalek = "1"
rand = "0.7"
*/

fn main() {
    let mut csprng = rand::rngs::OsRng {};
    let keypair = ed25519_dalek::Keypair::generate(&mut csprng);
    let jwk = ssi::jwk::JWK {
        params: ssi::jwk::Params::OKP(ssi::jwk::OctetParams {
            curve: "Ed25519".to_string(),
            public_key: ssi::jwk::Base64urlUInt(keypair.public.to_bytes().to_vec()),
            private_key: Some(ssi::jwk::Base64urlUInt(keypair.secret.to_bytes().to_vec())),
        }),
        public_key_use: None,
        key_operations: None,
        algorithm: None,
        key_id: None,
        x509_url: None,
        x509_certificate_chain: None,
        x509_thumbprint_sha1: None,
        x509_thumbprint_sha256: None,
    };
    println!("{}", serde_json::to_string(&jwk).unwrap());
}
```

**Comment by Arxcis** [comment]
@clehner This was extremely helpful. Thank you very much :pray:
