### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by JovanShandro** [spruceid/didkit#133]
**Describe the bug**
Building fails in Ubuntu 20.04 with the following message:
```
error: couldn't read src/../json-ld/src/lib.rs: No such file or directory (os error 2)
  --> src/lib.rs:26:1
   |
26 | mod json_ld;
   | ^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `ssi`
```

**To Reproduce**
Go through the installation process explained [here](https://spruceid.dev/docs/didkit/)  

**Expected behavior**
The building process should not fail

**Desktop (please complete the following information):**
My lsb_release -a command gives the following:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
The default browser is firefox 87.0

**Comment by sbihel** [comment]
Hi @JovanShandro,

Apologies for the outdated documentation -- you can run the following command in `ssi`:
```bash
$ git submodule update --init --recursive
```

This will pull `json-ld` and should fix the issue.

**Comment by JovanShandro** [comment]
@sbihel Thank you!
