### ISSUE TITLE
Is there support in DIDKit http for more than one issuer?

### ISSUE THREAD

**Issue by JovanShandro** [spruceid/didkit#134]
Hi!

From what I understood from the documentation, the server that is started with DIDKit-http will only use the provided keys for issuing a credential.
I wanted to ask is there support or a plan to add support for making this service work for more than one issuer? What I mean by this is e.g to have a single server running on port 9999 such that when a credential is to be issued, the key(s) that is/are provided initially are not the only ones that can be used for signing it, but some other key (for example one that could be sent with the request body) .

If I got it right, the only way to currently achieve using one server for many issuers is if multiple keys are passed on start, which means you have to know how many issuers you might have before starting the server.

(Please correct me in case I am wrong and have missed smth from the documentation.)

**Comment by clehner** [comment]
Hi @JovanShandro,
You are right that `didkit-http` currently can only issue proofs signing from the keys passed at startup. These can be for multiple issuers. But other keys cannot be added currently except by restarting the server with different arguments.

Passing a key in the HTTP request body could be useful if we want to implement [Universal Registrar drivers](https://github.com/decentralized-identity/universal-registrar/blob/main/docs/driver-development.md), as that is how some of them work.

Another way would be to add some routes for adding and removing keys. Requests to these routes should probably be authenticated somehow.

Another simpler way may be to load private keys from the filesystem given a directory where the keys are stored as files with filename derived from the key id or public key hash.

We should probably support one or more of these ways of signing with keys other than private keys passed at startup.
