### ISSUE TITLE
How to use did:web with DIDKit?

### ISSUE THREAD

**Issue by RomeldaB** [spruceid/didkit#135]
To create a did from a key pair in the demos from the documentation the following command is used:

```bash
didkit key-to-did-key -k issuer_key.jwk
```

How can a did:web did be created?

I tried using the following which resulted in errors:
```
didkit key-to-did-web -k issuer_key.jwk
didkit key-to-did web -k issuer_key.jwk
```

**Comment by clehner** [comment]
Hi @RomeldaB,
Unlike `did:key` and others, a `did:web` DID cannot generally be derived solely from a public key. To create a `did:web` DID, you must have a web server with HTTPS and put a DID document JSON file on it. We don't currently have a tool for automating this - but the `did:web` specification describes how to do it, here:
https://w3c-ccg.github.io/did-method-web/#create-register
Does this help?

**Comment by RomeldaB** [comment]
@clehner Yes, thank you!!
