### ISSUE TITLE
Update VC HTTP API to controller pattern

### ISSUE THREAD

**Issue by wyc** [spruceid/didkit#14]
Unfortunately, as we were just passing our tests, it seems that the spec has changed. Fortunately they don't look too drastic, only URL component ordering.

https://github.com/w3c-ccg/vc-http-api/pull/73

**Comment by clehner** [comment]
didkit-http was updated to use the controller pattern (`vc-http-api v0.0.2`) in https://github.com/spruceid/didkit/pull/102. But the routes are not yet versioned.
