### ISSUE TITLE
Evaluate support for SJCL

### ISSUE THREAD

**Issue by wyc** [spruceid/didkit#143]
How can we use SJCL to reduce binary size for JS/WASM builds, increase user optionality, and improve security? How would we have our WASM call out to external crypto? I imagine we'll need to support similar workflows, such as for HSM signing and native P-256 modules. I realize we have already enabled external signing with DIDKit--wondering about the shape of a cryptographic trait system that can be satisfied by multiple backends dependent on platform & support.

https://crypto.stanford.edu/sjcl/

**Comment by bumblefudge** [comment]
discussed on today's DIDKit sync; would NPM allow trait-style selective compilation? would we have to compile a distinct version for each combination of optional [crypto] dependencies?
