### ISSUE TITLE
Intermittent did:tz resolution error

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#176]
A test for `did:tz` fails: https://github.com/spruceid/didkit/runs/3001967237#step:10:123
But previously passed (same commit): https://github.com/spruceid/didkit/runs/3001318128

It looks like an error resulting from decoding the HTTPS request internal to the `did:tz` resolution:
```
$ didkit did-resolve did:tz:tz1LB6xh1Rf8k2WfqAKUuV5sKpQ5ySW3Y965
error decoding response body: missing field `items` at line 1 column 69
```

**Comment by sbihel** [comment]
We can either keep these tests but use them with a local sandbox, or move them to smoke/tests. But for now, I guess we can move them to examples and not run them as part of the CI?
