### ISSUE TITLE
`cargo install didkit-cli` is failing

### ISSUE THREAD

**Issue by vdods** [spruceid/didkit#196]
The error is
```
    Updating crates.io index
  Downloaded didkit-cli v0.1.0
  Downloaded 1 crate (29.0 KB) in 0.40s
  Installing didkit-cli v0.1.0
error: failed to compile `didkit-cli v0.1.0`, intermediate artifacts can be found at `/var/folders/wy/pzkn5xrs7338tvz2r51syqlw0000gn/T/cargo-installb5UtI5`

Caused by:
  failed to select a version for the requirement `crypto-mac = "^0.7"`
  candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
  location searched: crates.io index
  required by package `hmac v0.7.0`
      ... which is depended on by `hmac-drbg v0.2.0`
      ... which is depended on by `libsecp256k1 v0.3.2`
      ... which is depended on by `did-ethr v0.0.1`
      ... which is depended on by `didkit v0.2.0`
      ... which is depended on by `didkit-cli v0.1.0`
```

I had this same build error happen to me on a project that used libsecp256k1.  Unfortunately, it's not as simple as just bumping the version on libsecp256k1, because the latest version (0.6.0) is not backwards compatible (e.g. it changes the crate's module name from secp256k1 to libsecp256k1, among other things).  This version incompatibility seemed to crop up at some time, as if some crate was changed backward-incompatibly after the fact.

I've tried this build on two other (clean) systems, and verified that the same error occurs.  Anyone else getting this?

**Comment by clehner** [comment]
Hi @vdods,
We've migrated away from the libsecp256k1 crate in https://github.com/spruceid/ssi/pull/180 and https://github.com/spruceid/ssi/pull/271, which should fix this, but have yet to publish new versions of the `did-ethr` and `did-tz` crates with those changes. We will do this probably either as part of ssi v0.3 + didkit v0.3 releases, or by backporting the fix to the affected crates.

**Comment by sbihel** [comment]
`crypto-mac` 0.7 was un-yanked so this is now resolved. Apologies for the inconvenience. Discussion continues in #197 to ensure the latest stable release always works.
