### ISSUE TITLE
did:ethr doesn't support the spec it references

### ISSUE THREAD

**Issue by vdods** [spruceid/didkit#207]
The did-ethr resolver works great on etherium address DIDs (ones whose hex string is 40 chars long), but returns with `invalidDid` for public key hex DIDs (ones whose hex string is 66 chars long).  The spec that it ( https://github.com/spruceid/ssi/blob/6d82e3ef4f94c7c3292b4688e36a494bbcb24a07/did-ethr/src/lib.rs#L27 ) references is https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md -- partial support wouldn't necessarily be a problem, except that I'm unable to override the resolver (I'm using `didkit-cli` or equivalently `didkit-http`) to use a custom DID resolver for did:ethr (such as universal resolver).

I think this ticket belongs to both `ssi` and `didkit` repos, since there are resolution paths for both of them.  Though obviously the better solution is to have `ssi` support the whole did:ethr spec.

**Comment by vdods** [comment]
Looking through the code, the problem is that anything passed to `didkit` for `--did-resolver` just gets tacked onto a `Vec` that's populated by `DID_METHODS`, and so presumably this means that if a particular DID method has a hit with any of these built-in resolvers (in particular ssi crate's did_ethr), it gets handled fully by that resolver.  And in the case of did:ethr, the resolver is only partially implemented, so it reports an error and then quits, instead of falling through to another resolver.

A good solution would be to allow for DID-method-specific resolver override.  Using a hypothetical new form for didkit-cli's did-resolve command,
```
didkit did-resolve --did-resolver --did-resolver "did:ethr https://resolver.identity.foundation/1.0/identifiers/ did:ethr:ropsten:0x0392196025ba090066590125ff3e9173e09bf537ca9582abb4fea861d1f652c35e"
```
where depending on how CLI args are implemented (I'm not familiar enough with the particular CLI parser), overrides for multiple DID methods could be specified either by repeated use of the `--did-resolver` arg, or by passing a single comma-separated list of `did:method URL` values.

An easier but more brutish way would be to clarify in the `--help` message that the existing `--did-resolver` always acts as a fallback (this fact is pretty vague currently), and add a new CLI arg such as `--did-resolver-override` which simply prepends the given `HTTPDIDResolver` value to the `Vec` of DID resolvers in `ResolverOptions::to_resolver`, so that it gets tried before any of the built-in resolvers.

**Comment by vdods** [comment]
For reference, the disparity in didkit vs universal resolver I'm encountering can be seen using the following commands:

Not working:
```
didkit did-resolve --with-metadata did:ethr:ropsten:0x0392196025ba090066590125ff3e9173e09bf537ca9582abb4fea861d1f652c35e
```

Working:
```
curl -X GET https://resolver.identity.foundation/1.0/identifiers/did:ethr:ropsten:0x0392196025ba090066590125ff3e9173e09bf537ca9582abb4fea861d1f652c35e
```

**Comment by clehner** [comment]
Hi @vdods, thanks for opening this and suggesting ways to fix it.
I agree with the idea of adding DID-method-specific resolver options.
As a quick fix for using a different resolver, I've added the override option in #209. It can be used with the URIs you mention, as follows (`-R` as alias for `--did-resolver-override`):
```
didkit did-resolve --with-metadata -R https://resolver.identity.foundation/1.0/identifiers/ did:ethr:ropsten:0x0392196025ba090066590125ff3e9173e09bf537ca9582abb4fea861d1f652c35e
```

**Comment by wyc** [comment]
This is merged. Please give it a spin and let us know if it works for you.

**Comment by vdods** [comment]
This works great, thanks for getting to it so quick!

**Comment by wyc** [comment]
Appreciate your patience! I will close this for now, and we'll keep working on https://github.com/spruceid/ssi/issues/287 for a permafix. Thanks again for the reports.
