### ISSUE TITLE
Error compiling json crate in WASM

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#270]
https://github.com/spruceid/didkit/runs/5409011464?check_suite_focus=true#step:28:243

>  error: could not compile `json`

`cargo tree` shows `json v0.12.4` in use.

Building the `json` crate on its own (`cargo build --lib --release --target wasm32-unknown-unknown`) succeeds. wasm32 check in `ssi` passes also.

rustc memory use gets very high at the following step; maybe there is a compiler bug?
```
   Compiling did-pkh v0.1.0 (/home/cel/src/ssi/did-pkh)
warning: `did-ion` (lib) generated 4 warnings
   Compiling did-method-key v0.1.2 (/home/cel/src/ssi/did-key)
warning: `did-onion` (lib) generated 1 warning
warning: `ssi` (lib) generated 5 warnings
    Building [=======================> ] 424/427: json
```

This happens when using cargo 1.59.0, which has incremental compilation disabled: https://github.com/spruceid/didkit/pull/269#issuecomment-1059258832
These work:
- cargo 1.58.0 (f01b232bc 2022-01-19)
- cargo 1.61.0-nightly (3d6970d 2022-02-28)

A work around is added in 1786ba4e6b62a78a8dd853baaa78395c5b5c9eca to use v1.58 for CI. This can be removed when the next Rust stable version is released with incremental compilation fixed.

**Comment by sbihel** [comment]
Hasn't been an issue in the past few months. Will reopen if necessary.
