### ISSUE TITLE
Add `prepareIssuePresentation` for a web version

### ISSUE THREAD

**Issue by Harasz** [spruceid/didkit#273]
Hi,
I am using DIDKit [web](https://github.com/spruceid/didkit/tree/main/lib/web) version. There is an option to sign a verifiable credential with external sign method using `prepareIssueCredential` and `completeIssueCredential`. I would like to have such option also for verifiable presentations, do you have in plans implement this in the future?

**Comment by clehner** [comment]
Hi @Harasz, yes, I think this would be useful.

**Comment by Harasz** [comment]
You are so fast guys! I am really appreciate this :smile:

**Comment by sbihel** [comment]
Published in v0.2.1. If you can test it that'd be great :+1:

**Comment by Harasz** [comment]
Thank you a lot for a such detailed answer. I think we can close this issue :smile:
