### ISSUE TITLE
Node @spruceid/didkit is 1GB installed

### ISSUE THREAD

**Issue by mixmix** [spruceid/didkit#291]
![image](https://user-images.githubusercontent.com/2665886/163103629-8db20821-46a0-45e1-87e7-a58a9ca27005.png)

surely this is a mistake. This is unreal amount of disk usage

**Comment by clehner** [comment]
Some duplication of functionality in the dependencies could be reduced, e.g. openssl and ring (#113).

`jni` is in that list but doesn't need to be ([TODO](https://github.com/spruceid/didkit/blob/305481916434f97183c783106aff6f3f0056486c/lib/Cargo.toml#L43-L44)).

Possibly some dependencies could be removed in favor of using core node modules. e.g. the `openssl` crate is brought in by `reqwest` via `hyper-tls`, for HTTP(S) client functionality used in `did:web` and a few other places; but Node.js already provides a `http` and `https` module that could be used to make HTTP(S) requests. To do this without adding Node.js-specific code in the `ssi` library might mean making the HTTP(S) client a part of the interface for `ssi`'s functions.

**Comment by sbihel** [comment]
I don't think this it's a code redundancy issue, it's just build artefacts. I think if the binary is not found from Github releases it will build it locally, and thus leave the `target` directory behind. So if we decide to keep maintaining the Neon version, we'd need to fix:
1. the support for various architectures and OS; and
2. clean up the compilation step that's used as a fallback.

**Comment by sbihel** [comment]
Neon binding support was dropped in #306
