### ISSUE TITLE
Add support for prepare and complete issue in @spruceid/didkit

### ISSUE THREAD

**Issue by JGiter** [spruceid/didkit#302]
We've being created credentials by `prepareIssueCredential`, `completeIssueCredential` and their presentation analogues. Due to https://github.com/spruceid/didkit/issues/301 we are considering switching to @spruceid/didkit, but this build doesn't have `prepare..` and `complete...` functions. Are their any plans to include these in neon build?

**Comment by sbihel** [comment]
We have decided to stop maintaining the Neon version for the time being. Apologies for the confusion as we haven't removed the code from the repo yet.
