### ISSUE TITLE
Python Django examples throws error - no running event loop

### ISSUE THREAD

**Issue by demos2022** [spruceid/didkit#307]
While running the python-django example program, the error - no running event loop gets thrown when the line -verification_method = didkit.key_to_verification_method("key", key) in issue_credential.py file gets invoked.
Attached is the screenshot.
![screenshot_pythondjangoerror](https://user-images.githubusercontent.com/109317376/184693324-48d10441-5607-4f53-87b6-93d3acaf711a.PNG)

**Comment by sbihel** [comment]
Whilst I fix the various pipelines, you will find the updated example here: https://github.com/spruceid/didkit-python/tree/feat/examples/examples/python_django
