### ISSUE TITLE
implement AWAKE inbound/outbound upgrade

### ISSUE THREAD

**Issue by chunningham** [spruceid/didkit#325]
[Awake](https://github.com/ucan-wg/awake) can be used the same way [Noise](https://docs.rs/libp2p/latest/libp2p/noise/struct.NoiseConfig.html#impl-InboundUpgrade%3CT%3E-for-NoiseConfig%3CIK%2C%20C%2C%20()%3E) to provide a mutually-authorised encrypted channel between peers.

**Comment by sbihel** [comment]
I assume this was meant for Kepler?
