### ISSUE TITLE
Support for Selective Disclosure using bbs+ signatures

### ISSUE THREAD

**Issue by kenshin171** [spruceid/didkit#345]
Thanks for your work on this library, may I ask whether selective disclosure with bbs+ signatures will be released anytime soon? 
I notice that there is work being done on both didkit and the ssi libraries.

**Comment by sbihel** [comment]
DIDKit will gain support once `ssi` does. I will close this issue as duplicate of https://github.com/spruceid/ssi/issues/275, but may reopen once that issue is closed.
