### ISSUE TITLE
Failed to build didkit for iOS simulator

### ISSUE THREAD

**Issue by kangminhao** [spruceid/didkit#347]
When I was trying to build an iOS framework, I encountered some problems. When running make -C lib ../target/test/ios.stamp, I couldn't pass the unit tests. The error message was: ".../Build/Products/Debug-iphonesimulator/DIDKitSwiftTests.xctest/DIDKitSwiftTests' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))))". 

Has anyone encountered the same issue and resolved it?

Xcode: 14.3
Device: Macbook M1 Pro

**Comment by sbihel** [comment]
Closing as duplicate of #297
