### ISSUE TITLE
Flutter : Failed to load dynamic library 'libdidkit.so': dlopen failed: library "libdidkit.so" not found

### ISSUE THREAD

**Issue by shabaadh** [spruceid/didkit#380]
Invalid argument(s): Failed to load dynamic library 'libdidkit.so': dlopen failed: library "libdidkit.so" not found
Ive downloaded the zip file of copied the did kit package folder to my project.libdidkit.so cannot be opened in vscode also

**Comment by shabaadh** [comment]
when following this step, maybe this could be the issue(command not completed successfully): 
cd deps/didkit/lib

# For Android development, we must cross compile the Rust library for
# several Android binary targets.  You will see simmilar messages appear
# multiple times while this runs.
#
# You only need to do this when building for Android.
make ../target/test/android.stamp



/Users/admin/.zprofile:1: no such file or directory: /opt/homebrew/bin/brew
admin@Admins-MacBook-Pro lib % make ../target/test/android.stamp
mkdir -p ../target/jvm
javac java/main/com/spruceid/DIDKit.java -d ../target/jvm -cp java/main -source 1.7 -target 1.7
warning: [options] bootstrap class path not set in conjunction with -source 7
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
jar -cf ../target/didkit.jar -C ../target/jvm com/spruceid/DIDKit.class -C ../target/jvm com/spruceid/DIDKitException.class
PATH=/toolchains/llvm/prebuilt/darwin-x86_64/bin:"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/admin/.cargo/bin" \
	cargo build --lib --release --target i686-linux-android
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
   Compiling cfg-if v1.0.0
   Compiling subtle v2.5.0
   Compiling libc v0.2.153
   Compiling typenum v1.17.0
   Compiling const-oid v0.9.6
   Compiling generic-array v0.14.7
   Compiling zeroize v1.7.0
   Compiling serde v1.0.196
   Compiling once_cell v1.19.0
   Compiling base64ct v1.6.0
   Compiling memchr v2.7.1
   Compiling pin-project-lite v0.2.13
   Compiling cpufeatures v0.2.12
   Compiling thiserror v1.0.56
   Compiling smallvec v1.13.1
   Compiling static_assertions v1.1.0
   Compiling futures-core v0.3.30
   Compiling futures-io v0.3.30
   Compiling byteorder v1.5.0
   Compiling pem-rfc7468 v0.7.0
   Compiling value-bag v1.7.0
   Compiling itoa v1.0.10
   Compiling der v0.7.8
   Compiling slab v0.4.9
   Compiling log v0.4.20
   Compiling arrayref v0.3.7
   Compiling libm v0.2.8
   Compiling num-traits v0.2.17
   Compiling getrandom v0.2.12
   Compiling futures-sink v0.3.30
   Compiling bytes v1.5.0
   Compiling rand_core v0.6.4
   Compiling base16ct v0.2.0
   Compiling data-encoding v2.5.0
   Compiling ff v0.13.0
   Compiling group v0.13.0
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling data-encoding-macro v0.1.14
   Compiling crypto-bigint v0.5.5
   Compiling digest v0.10.7
   Compiling sha2 v0.10.8
   Compiling hmac v0.12.1
   Compiling spki v0.7.3
   Compiling pkcs8 v0.10.2
   Compiling signature v2.2.0
   Compiling hkdf v0.12.4
   Compiling sec1 v0.7.3
   Compiling base-x v0.2.11
   Compiling ppv-lite86 v0.2.17
   Compiling pin-utils v0.1.0
   Compiling hex v0.4.3
   Compiling rand_chacha v0.3.1
   Compiling num-integer v0.1.45
   Compiling futures-channel v0.3.30
   Compiling elliptic-curve v0.13.8
   Compiling lexical-util v0.8.5
   Compiling futures-task v0.3.30
   Compiling unsigned-varint v0.7.2
   Compiling crunchy v0.2.2
   Compiling crossbeam-utils v0.8.19
   Compiling futures-util v0.3.30
   Compiling rand v0.8.5
   Compiling multibase v0.9.1
   Compiling rfc6979 v0.4.0
   Compiling ahash v0.8.7
   Compiling zerocopy v0.7.32
   Compiling ryu v1.0.16
   Compiling serde_json v1.0.113
   Compiling ecdsa v0.16.9
   Compiling tracing-core v0.1.32
   Compiling spin v0.5.2
   Compiling parking v2.2.0
   Compiling lazy_static v1.4.0
   Compiling num-iter v0.1.43
   Compiling hashbrown v0.13.2
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling tracing v0.1.40
   Compiling concurrent-queue v2.4.0
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling crypto-bigint v0.3.2
   Compiling pem-rfc7468 v0.3.1
   Compiling const-oid v0.7.1
   Compiling opaque-debug v0.3.0
   Compiling tiny-keccak v2.0.2
   Compiling num-bigint-dig v0.8.4
   Compiling ahash v0.7.7
   Compiling lexical-parse-float v0.8.5
   Compiling lexical-write-float v0.8.5
   Compiling curve25519-dalek v4.1.2
   Compiling uint v0.9.5
   Compiling android_system_properties v0.1.5
   Compiling fixed-hash v0.7.0
   Compiling fnv v1.0.7
   Compiling contextual v0.1.6
   Compiling utf8-decode v1.0.1
   Compiling bitflags v2.4.2
   Compiling locspan v0.7.16
   Compiling pct-str v1.2.0
   Compiling iana-time-zone v0.1.60
   Compiling lexical-core v0.8.5
   Compiling primitive-types v0.9.1
   Compiling der v0.5.1
   Compiling sha2 v0.9.9
   Compiling spki v0.5.4
   Compiling primeorder v0.13.6
   Compiling mio v0.8.10
   Compiling socket2 v0.5.5
   Compiling num_cpus v1.16.0
   Compiling openssl-src v300.2.2+3.2.1
   Compiling vcpkg v0.2.15
   Compiling keccak v0.1.5
   Compiling ryu-js v0.2.2
   Compiling android-tzdata v0.1.1
   Compiling pkg-config v0.3.29
   Compiling chrono v0.4.33
   Compiling sha3 v0.10.8
   Compiling indexmap v1.9.3
   Compiling num-bigint v0.4.4
   Compiling tokio v1.36.0
   Compiling pkcs8 v0.8.0
   Compiling keccak-hash v0.7.0
   Compiling openssl-sys v0.9.99
   Compiling bs58 v0.4.0
   Compiling hashbrown v0.12.3
   Compiling lexical v6.1.1
   Compiling iref v2.2.3
   Compiling http v0.2.11
   Compiling ripemd160 v0.9.1
   Compiling event-listener v4.0.3
   Compiling k256 v0.13.3
   Compiling ed25519 v2.2.3
   Compiling langtag v0.3.4
   Compiling base64 v0.12.3
   Compiling ryu_floating_decimal v0.1.0
   Compiling rdf-types v0.12.19
   Compiling ssi-crypto v0.1.1 (/Users/admin/Documents/flutter projects/didkit_demo/deps/ssi/ssi-crypto)
   Compiling ring v0.17.7
error: failed to run custom build command for `ring v0.17.7`

Caused by:
  process didn't exit successfully: `/Users/admin/Documents/flutter projects/didkit_demo/deps/didkit/target/release/build/ring-896bc256e3ba5aa4/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_7_
  OPT_LEVEL = Some("3")
  TARGET = Some("i686-linux-android")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CC_i686-linux-android
  CC_i686-linux-android = None
  cargo:rerun-if-env-changed=CC_i686_linux_android
  CC_i686_linux_android = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  cargo:rerun-if-env-changed=CFLAGS_i686-linux-android
  CFLAGS_i686-linux-android = None
  cargo:rerun-if-env-changed=CFLAGS_i686_linux_android
  CFLAGS_i686_linux_android = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  running: "i686-linux-android-clang" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "include" "-I" "/Users/admin/Documents/flutter projects/didkit_demo/deps/didkit/target/i686-linux-android/release/build/ring-efb4ec6220abe5bb/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-o" "/Users/admin/Documents/flutter projects/didkit_demo/deps/didkit/target/i686-linux-android/release/build/ring-efb4ec6220abe5bb/out/crypto/curve25519/curve25519.o" "-c" "crypto/curve25519/curve25519.c"

  --- stderr


  error occurred: Failed to find tool. Is `i686-linux-android-clang` installed?


warning: build failed, waiting for other jobs to finish...
make: *** [../target/i686-linux-android/release/libdidkit.so] Error 101

**Comment by shabaad** [comment]
Use forked repository https://github.com/alan-turing-institute/trustchain-mobile.git 
and follow the instructions from install_trustchain_mobile.md file to setup the project.
This is updated latest repo.
Android and iOS running successfully without any issues.

**Comment by shabaadh** [comment]
Running fine on android and iOS by using the above repo
