### ISSUE TITLE
Release commit incorrect and history includes unattributed commit

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#51]
Commits from #49 were rebased onto #50, but this breaks correspondance between the `v0.1.0` release commit, changelog, and the initial release blog post. Also, the commit merged in #50 does not have author/committer info (the commit author is "ec2-user"). I propose to rewrite the last three commits on `main`, rebasing rebase #50 onto the original #49. @wyc would this be okay? @theosirian can I amend your commit from #50 to show authorship as in your other commits?

**Comment by wyc** [comment]
Sounds great, thanks. I reviewed the changes and found them okay, but did not consider attribution. Great catch. I believe it’s time to add contribution guidelines to our public repos and automated enforcement  where possible.

**Comment by clehner** [comment]
`main` reset to f582a25ec054423f6b47ecfbe5885b605ee4793f as proposed
