### ISSUE TITLE
Credible bug: [BUG] Unable to build DIDKit due to multiple definitions of sha256 and generate_ed25519

### ISSUE THREAD

**Issue by Mikerah** [spruceid/didkit#64]
**Describe the bug**
When building DIDKit according to the instructions found [here](https://spruceid.dev/docs/didkit/), I encountered to errors relating to duplication of definitions of sha256 and generate_ed25519. These definitions are actually found in the ssi crate and is causing the building process to fail.

These are the outputs:

```
error[E0428]: the name `sha256` is defined multiple times
  --> /home/mikerah/Documents/Projects/ssi/src/hash.rs:13:1
   |
4  | pub fn sha256(data: &[u8]) -> Result<[u8; 32], Error> {
   | ----------------------------------------------------- previous definition of the value `sha256` here
...
13 | pub fn sha256(data: &[u8]) -> Result<[u8; 32], Error> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `sha256` redefined here
   |
   = note: `sha256` must be defined only once in the value namespace of this module
```

```
error[E0201]: duplicate definitions with name `generate_ed25519`:
   --> /home/mikerah/Documents/Projects/ssi/src/jwk.rs:206:5
    |
179 | /     pub fn generate_ed25519() -> Result<JWK, Error> {
180 | |         use ring::signature::KeyPair;
181 | |         let rng = ring::rand::SystemRandom::new();
182 | |         let doc = ring::signature::Ed25519KeyPair::generate_pkcs8(&rng)?;
...   |
202 | |         })
203 | |     }
    | |_____- previous definition of `generate_ed25519` here
...
206 | /     pub fn generate_ed25519() -> Result<JWK, Error> {
207 | |         let mut csprng = rand::rngs::OsRng {};
208 | |         let keypair = ed25519_dalek::Keypair::generate(&mut csprng);
209 | |         let sk_bytes = keypair.secret.to_bytes();
...   |
225 | |         })
226 | |     }
    | |_____^ duplicate definition

```

**To Reproduce**
Steps from [DIDKit docs](https://spruceid.dev/docs/didkit/)
1. git clone https://github.com/spruceid/ssi
2. git clone https://github.com/spruceid/didkit
3.  cd didkit/
4. cargo build

**Expected behavior**
Expected cargo build to complete without any errors.

**Desktop (please complete the following information):**
 - OS: Fedora 32, 64-bit
 - Browser: Firefox

**Comment by wyc** [comment]
Thanks for opening an issue @Mikerah, please try the instructions here to exclude the WASM package for now: https://github.com/spruceid/didkit#manual

Specifically, with our introduction of WASM, there were competing features for `ssi`. We believe that packaging for crates.io and adding some more sophistication in our build process will resolve this.

We have tracked this issue more broadly here to ensure it doesn't re-occur: https://github.com/spruceid/didkit/issues/63

**Comment by wyc** [comment]
Hi @Mikerah, with https://github.com/spruceid/didkit/pull/65 I believe this should be resolved. Could you please confirm? Thanks.

**Comment by Mikerah** [comment]
I can confirm that with #65, I was able to build didkit.
Closing...
