### ISSUE TITLE
DIDKit Feature request: [FEATURE] DID Onion & TorGap

### ISSUE THREAD

**Issue by ChristopherA** [spruceid/didkit#68]
**Is your feature request related to a problem? Please describe.**

I’m desire a correlation-resistant endpoint.

**Describe the solution you'd like**

Support [`did:onion`](https://github.com/BlockchainCommons/did-method-onion) and your other DIDs over a [TorGap](https://github.com/BlockchainCommons/TorGap).

**Describe alternatives you've considered**

DID-BTCR is correlation resistant if you communicate with bitcoin-core over a TorGap. We have implemented Bitcoin Standup Scripts (Linux & VPS) and Gordian Server that do this.

/cc @gorazdko @wolfmcnally @henkvancann

**Comment by wyc** [comment]
Hi @ChristopherA and @gorazd, with https://github.com/spruceid/didkit/pull/125 and https://github.com/spruceid/ssi/pull/147, I believe we have did-onion support. Could you please describe how two DIDs would initiate a TorGap comms link, and how messaging routing works? I am reading the documentation but any additional implementer-focused overviews/tips would be much appreciated.

**Comment by ChristopherA** [comment]
Both parties can get the x25519 key agreement keys from each other’s did:onion documents. Then they can just do a simple key agreement with each other, asymmetrically encrypting with the shared key unique between the two pairs (4 keys). An example of x25519 key agreement is [RFC 7748]( https://tools.ietf.org/html/rfc7748) & [ssh](https://tools.ietf.org/id/draft-ietf-curdle-ssh-curves-12.html).

This is only required some scenarios for mutual trust — unique to did:onion as compared to other DIDs you know since you were able to retrieve did:onion document at all, that the server had control of its private key associated with the public key embedded in its onion address. Both parties can do that independent without the extra step of key agreement.

**Comment by wyc** [comment]
Thanks for the details and references. Is there a preferred transport that you typically use with TorGap? Would TLS/mTLS be ideal for now?

**Comment by ChristopherA** [comment]
Technically you don’t need TLS with tor to an onion address, as it encrypts the transport. Many sites do anyhow, but by default our demo does not.

**Comment by wyc** [comment]
Thanks for the clarification. `didkit` can now resolve did-onion with a running local proxy server. If this suits Blockchain Commons, we'd be glad to have DIDKit added under the implementation section!

**Comment by ChristopherA** [comment]
Sounds great!

I’m particularly looking forward to .git files being signed with detached VCs so we can have better software provenance.

**Comment by wyc** [comment]
I think @dhuseby and @mlodder are working on that

**Comment by agropper** [comment]
I'm a huge fan of didkit's approach to SSI. We need libraries that support
did:key, did:web, and at least one or two other categories of dids in the
rubric sense. I'd like to understand where did:onion and TorGap fit in.
When applied to dids that identify human personas, I'm particularly
interested in
(a) ways we expect Verifiable Presentations to prove that two VCs issued to
two separate same-domain did:key are actually under the control of the same
subject / controller, and
(b) ways to avoid correlation of service endpoints to a self-sovereign
agent in a did:peer or other method that allows control over a service
endpoint.

Is there a reference or write-up that explains either (a) or (b) as it
relates to did:onion and/or TorGap?

- Adrian

**Comment by ChristopherA** [comment]
> Is there a reference or write-up that explains either (a) or (b) as it relates to did:onion and/or TorGap?

did:onion transport is inherently non-correlatable. However, if your VCs themselves correctable, the transport is not going to help any. 

Using tor to connect onion address supports overall privacy through:

* service anonymity - you don't get to know where the onion service is hosted
*  identity psuedonymity - through a self-issued 25519 public key (both parties - the tor browser and onion service - have a public keys , but only the onion service's key is persistent)
* the internet traffic of both the tor browser and that of the onion server are encrypted and non-correalatable
* both browser and onion server have some measure of routing censorship-resistance.

[Torgap architecture](https://github.com/BlockchainCommons/torgap/) adds to this a design a seperation-of-interests and reduces single-points-of-failure. 

Torgap with did:onion has one other odd features in the did/vc world, which the act of connecting to an onion server and getting its did document, the holder knows that the server has control of the private key if they match, as you can't connect to the onion server unless it has that control.

See the [Torgap FAQ]( https://github.com/BlockchainCommons/torgap/blob/master/Docs/FAQ.md) on the advantages of did:onion and torgaps.

-- Christopher Allen
