### ISSUE TITLE
Verify credentials when verifying presentation

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#78]
As discussed in https://github.com/w3c-ccg/vc-http-api/issues/111, it seems that verifying a presentation in `vc-http-api` is supposed to include verifying embedded verifiable credentials rather than expecting the client to verify them separately. DIDKit should probably be updated to follow this behavior in its API.

**Comment by bumblefudge** [comment]
I believe the consensus is that verifying VCs as well is default behavior turned off with a flag-- I have already heard examples of both being floated among users of the API!
