### ISSUE TITLE
Reset main to remove WIP commits

### ISSUE THREAD

**Issue by clehner** [spruceid/didkit#80]
Commits 3f3c6eff875db0b3e3de0765a4e4fd907b0d9e72 to df648eb102215600e17cae18a2d4a9e6062466a3 appear to be work-in-progress/development commits. I would like to reset `main` from df648eb102215600e17cae18a2d4a9e6062466a3 to 4c170bf847bcc3d25a2708264045bafaee99fb98 to remove these. They could be re-added via a separate branch and PR.

**Comment by wyc** [comment]
This is fine, thanks.

**Comment by clehner** [comment]
`main` reset; previous commit stored at branch `xp-tweaks`
```To github.com:spruceid/didkit.git                                               
 + df648eb...4c170bf main -> main (forced update)
 + 414c7e3...df648eb xp-tweaks -> xp-tweaks (forced update)
```

**Comment by bumblefudge** [comment]
my mistake, apologies!
